# ???oneCoupon????????
# ???? (C) [2024-??] [????????????]
# ???????
#
# 1. ?????
#    ??????????????????????[????????????]?????????
#    "??"???????????????????????????
#
# 2. ????
#    ?????????????????????????????????????????????????????
#    a. ??[????????????]???????????????????????????????
#    b. ?????????????????????[????????????]??????
#
# 3. ????
#    ????"??"???????????????????????????????????????????
#    ???????[????????????]??????????????????????????????????????????????????????????
#
# 4. ???????
#    a. ??[????????????]?????????????????????????????????????????????
#    b. ????????????????[????????????]????????????????????????????????????????????????
#    c. ????????????????????[????????????]???????????????????????????????????????
#
# 5. ????
#    a. [????????????]??????????????
#    b. ???????????????????
#
# ??[????????????]?????????????????????
#
# ?????[????????????]???????????

server:
  port: 10020

spring:
  application:
    name: oneCoupon-engine